apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy-v1  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-deploy-v1 
  template:
    metadata:
      labels:
        app: my-deploy-v1 
    spec:
      containers:
      - name: my-deploy-v1  
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-service-v1  
spec:
  type: LoadBalancer
  selector:
    app: my-deploy-v1 
  ports:
  - port: 80
    targetPort: 80
